### ISSUE TITLE
Edit in GitHub floats outside of content area on Mobile

### ISSUE THREAD

**Issue by mikemccamon** [OWASP/www--site-theme#29]

**Comment by victoriadrake** [comment]
This occurs due to the flow of the grid on smaller screens for the pages that are missing the `nav` element. You can see this by deleting the `nav` node in developer tools:

![Screenshot from 2019-12-17 11-49-22](https://user-images.githubusercontent.com/24644237/71017464-9729cf80-20c4-11ea-8d6a-30f960b41942.png)

![Screenshot from 2019-12-17 11-49-47](https://user-images.githubusercontent.com/24644237/71017019-f63b1480-20c3-11ea-946c-51e38d0f0cd8.png)

The `nav` element, if it is meant to be utilized, should be placed on all pages.

**Comment by victoriadrake** [comment]
This appears to have been resolved from commits yesterday.
