### ISSUE TITLE
Removing items in sidebar

### ISSUE THREAD

**Issue by drwetter** [OWASP/www--site-theme#39]
Hi,

in the subdirectorie of our chapter I rather want a proper navigation on the top right side of the page and not the text "The OWASP Foundation works to improve the security of software through its community-led open source software projects, ..."

See e.g. https://www2.owasp.org/www-chapter-germany/stammtische/ .

Is there any way I can remove or move this text?

Thx, Dirk

**Comment by bkimminich** [comment]
This text is quite obstrusive on all pages imho. Isn't this more something for a generic footer? Or at least push it to the very bottom of the sidenav?

**Comment by bkimminich** [comment]
Btw, on mobile devices with stacked layout the whole sidenav is below the content anyway, which makes it rather useless for important links and navigation alike.

**Comment by kingthorin** [comment]
Could we get a response on this?

**Comment by danybr0** [comment]
@drwetter, I think you can remove this text in the (standard/general) sidebar. But idk where I could find it

**Comment by hblankenship** [comment]
For chapters and, in this case, sub-chapters, it make sense to keep that text.  There are other ways for chapters with pages that are not themselves chapters and projects with multiple pages to not have that text.  The purpose of the text is so that, if someone comes to the page without knowing much about OWASP, they can read that blurb an have an idea.
